name: Add Label on Project Status Change

permissions:
  contents: read
  issues: write

on:
  workflow_dispatch:
    inputs:
      project_ids:
        description: 'Project IDs (comma-separated)'
        required: true
        default: 'PVT_kwDOAjmOms4BUHYq,PVT_kwDOAjmOms4BMOXr,PVT_kwDOAjmOms4BHSE3,PVT_kwDOAjmOms4A4UrU,PVT_kwDOAjmOms4Ax-qc,PVT_kwDOAjmOms4Ap3zU,PVT_kwDOAjmOms4AjKru,PVT_kwDOAjmOms4Ai2VW,PVT_kwDOAjmOms4ATX2f'
      status_value:
        description: 'Status value to match'
        required: false
        default: 'Need To Verify'
      label_to_add:
        description: 'Label to add'
        required: false
        default: 'kind/need-to-verify'
  schedule:
    - cron: '0 * * * *'  # Every hour

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: fix/workflow-project-status

      - name: Run add-label script
        env:
          PROJECT_IDS: ${{ github.event.inputs.project_ids }}
          STATUS_VALUE: ${{ github.event.inputs.status_value }}
          LABEL_TO_ADD: ${{ github.event.inputs.label_to_add }}
        run: |
          ./scripts/add-label.sh "$PROJECT_IDS" "$STATUS_VALUE" "$LABEL_TO_ADD"
